CREATE TABLE IF NOT EXISTS User(UserId INTEGER PRIMARY KEY AUTOINCREMENT,Username TEXT,Password TEXT, UserTypeId INTEGER  ,UNIQUE(Username, UserTypeId));



CREATE TABLE IF NOT EXISTS Course(CourseId INTEGER PRIMARY KEY AUTOINCREMENT,CourseName TEXT ,UNIQUE(CourseName));



CREATE TABLE IF NOT EXISTS Test(TestId INTEGER PRIMARY KEY AUTOINCREMENT,TestName TEXT,CourseId INTEGER, CreatedBy INTEGER ,UNIQUE(TestName,CourseId,CreatedBy));



CREATE TABLE IF NOT EXISTS UserTestMap(UserTestMapId INTEGER PRIMARY KEY AUTOINCREMENT,TestId INTEGER,UserId INTEGER);


CREATE TABLE IF NOT EXISTS Topic(TopicId INTEGER PRIMARY KEY AUTOINCREMENT,TopicName TEXT);



CREATE TABLE IF NOT EXISTS QuestionType(QuestionTypeId INTEGER PRIMARY KEY AUTOINCREMENT,QuestionTypeDescription TEXT,IsAutoGrading INTEGER);



CREATE TABLE IF NOT EXISTS Question(QuestionId INTEGER PRIMARY KEY AUTOINCREMENT,QuestionBody TEXT,QuestionTypeId INTEGER, TopicId INTEGER,TestId INTEGER, QuestionAttachments TEXT);


CREATE TABLE IF NOT EXISTS AnswerOption(AnswerOptionId INTEGER PRIMARY KEY AUTOINCREMENT,OptionBody TEXT,IsCorrect INTEGER,QuestionId INTEGER);


CREATE TABLE IF NOT EXISTS UserAnswer(UserAnswerId INTEGER PRIMARY KEY AUTOINCREMENT,QuestionId INTEGER, OptionSelected INTEGER,IsCorrect INTEGER, UserId INTEGER ,AnswerBody TEXT, AnswerAttachment1 BLOB,	AnswerAttachment2 BLOB,	AnswerAttachment3 BLOB);






